version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:6.0
    container_name: ecommerce-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ecommerce
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - ecommerce-network

  # Redis Service (for caching)
  redis:
    image: redis:7-alpine
    container_name: ecommerce-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ecommerce-network

  # API Service
  api:
    build: .
    container_name: ecommerce-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/ecommerce?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-here-make-it-long-and-complex
      JWT_EXPIRE: 7d
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # Add your payment gateway credentials here
      STRIPE_PUBLISHABLE_KEY: pk_test_your_stripe_key
      STRIPE_SECRET_KEY: sk_test_your_stripe_key
      RAZORPAY_KEY_ID: your_razorpay_key_id
      RAZORPAY_KEY_SECRET: your_razorpay_key_secret
      # Email configuration
      EMAIL_SERVICE: gmail
      EMAIL_USER: your-email@gmail.com
      EMAIL_PASS: your-app-password
    depends_on:
      - mongodb
      - redis
    networks:
      - ecommerce-network
    volumes:
      - ./uploads:/app/uploads

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: ecommerce-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    networks:
      - ecommerce-network

volumes:
  mongodb_data:
  redis_data:

networks:
  ecommerce-network:
    driver: bridge
